# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Work/Codes/Realtime/gtwizard_tx_demo/gtwizard_tx_demo/gtwizard_tx_demo.srcs/sources_1/ip/gtwizard_line_tx/gtwizard_line_tx.xci
# IP: The module: 'gtwizard_line_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Work/Codes/Realtime/gtwizard_tx_demo/gtwizard_tx_demo/gtwizard_tx_demo.gen/sources_1/ip/gtwizard_line_tx/gtwizard_line_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_line_tx'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Work/Codes/Realtime/gtwizard_tx_demo/gtwizard_tx_demo/gtwizard_tx_demo.gen/sources_1/ip/gtwizard_line_tx/gtwizard_line_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_line_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Work/Codes/Realtime/gtwizard_tx_demo/gtwizard_tx_demo/gtwizard_tx_demo.srcs/sources_1/ip/gtwizard_line_tx/gtwizard_line_tx.xci
# IP: The module: 'gtwizard_line_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Work/Codes/Realtime/gtwizard_tx_demo/gtwizard_tx_demo/gtwizard_tx_demo.gen/sources_1/ip/gtwizard_line_tx/gtwizard_line_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_line_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Work/Codes/Realtime/gtwizard_tx_demo/gtwizard_tx_demo/gtwizard_tx_demo.gen/sources_1/ip/gtwizard_line_tx/gtwizard_line_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_line_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
